# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19
    working_directory: ~/repo
    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "laravel/composer.json" }}

      - run:
          working_directory: laravel
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "laravel/composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "laravel/package.json" }}
      - run:
          working_directory: laravel
          command: npm install

      - save_cache:
          key: node-v1-{{ checksum "laravel/package.json" }}
          paths:
            - node_modules

      - run:
          name: prapare DB
          working_directory: laravel
          command: |
            touch storage/testing.sqlite
            php artisan migrate --env=testing --database=sqlite_testing --force

      - run:
          name: run phpunit
          working_directory: laravel
          command: |
            echo $ENV_FILE | base64 --decode > .env
            vendor/bin/phpunit

      - run:
          name: lint php
          working_directory: laravel
          command: |
            composer phpstan

      # run tests with phpunit or codecept
#      - run:
#          working_directory: laravel
#          command: ./vendor/bin/phpunit
#      - run:
#          working_directory: laravel
#          command: ./vendor/bin/codecept build
#      - run:
#          working_directory: laravel
#          command: ./vendor/bin/codecept run
